apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2RmDMRecIR1auushL9gPNeBtN9ut85iSgpC_P1afhctZG4.yvYM3W5qxIT5v1eA8FwuEmGHQBKPDfehpVt0aHRCdHc
